# Generated by Django 5.2.1 on 2025-05-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orderplaced_assigned_date_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='delivery_boy',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='assigned_date',
        ),
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
